site_name: Mail2Cloud Onboarding

# Configuration
site_dir: site
theme:
  name: material
  icon:
    logo: material/cloud-upload
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
extra_css:
 - 'stylesheets/unibe.css'
use_directory_urls: false

# Copyright footer
copyright: 'Copyright &copy; University of Bern, IT Service Office'
# Social links at botoom right
repo_name: 'idci-unibe-ch/sites-mail2cloud'
repo_url: 'https://github.com/idci-unibe-ch/sites-mail2cloud'
edit_uri: ''

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  # - codehilite:
  #     guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html

plugins:
  - search

nav:
  - Home: index.md
  - Vor der Migration: migration/pre-migration.md
  - Nach der Migration: migration/post-migration.md
  - Unterstützte Clients: migration/supported-clients.md
  - MFA Timings und MEM: migration/mfa-mem.md
  - Neue Möglichkeiten: migration/new-possibilities.md
  #   - Migrationsdaten: migration/migration-dates.md
  #   - Migrationsablauf: migration/migration-procedure.md
  #   - Kommunikation: migration/migration-communication.md
  #   - Checkliste IT-Staff: migration/migration-checklist-itstaff.md
  # - Anleitungen:
  #   - Anmeldetypen: tutorials/tutorials-logins.md