site_name: Mail2Cloud Onboarding

# Configuration
site_dir: site
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
extra_css:
 - 'stylesheets/unibe.css'
use_directory_urls: false

# Copyright footer
copyright: 'Copyright &copy; University of Bern, IT Service Office'
# Social links at botoom right
repo_name: 'idci-unibe-ch/sites-mail2cloud'
repo_url: 'https://github.com/idci-unibe-ch/sites-mail2cloud'
edit_uri: ''

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list

plugins:
  - search

nav:
  - Home: index.md
  # - Namenskonventionen: conventions/naming-conventions.md
  # - Migration:
  #   - Migrationsdaten: migration/migration-dates.md
  #   - Migrationsablauf: migration/migration-procedure.md
  #   - Kommunikation: migration/migration-communication.md
  #   - Checkliste IT-Staff: migration/migration-checklist-itstaff.md
  # - Anleitungen:
  #   - Anmeldetypen: tutorials/tutorials-logins.md